Repository bookkbookk/bookkbookk, pull requests merged in 2023-10, with the labels that each got.

#10 [FE] 디자인 시스템 구축
  README.md
  fe/index.html
  fe/public/favicon.ico
  fe/public/favicon.svg
  fe/src/App.style.ts
  fe/src/App.tsx
  fe/src/assets/fonts/PretendardVariable.woff2
  fe/src/assets/icons/google.svg
  fe/src/assets/icons/logo.svg
  fe/src/assets/images/brand-circle.svg
  fe/src/assets/images/brand.svg
  fe/src/components/Landing/Header.tsx
  fe/src/components/Landing/Main.tsx
  fe/src/components/Landing/index.style.ts
  fe/src/components/common/ThemeSwitch/ThemeSwitch.style.ts
  fe/src/components/common/ThemeSwitch/ThemeSwitch.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/Landing.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/OAuth.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useTheme.ts
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/designSystem.ts
  fe/src/styles/emotion.d.ts
  fe/src/styles/theme/ThemeProvider.tsx
  fe/src/styles/theme/palette.ts
  fe/src/styles/theme/typography.ts
  fe/src/vite-env.d.ts
Labels: UI, FE

#11 [FE] Sprint #01 프론트 작업
  README.md
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc.json
  fe/README.md
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.svg
  fe/public/mockServiceWorker.js
  fe/src/App.style.ts
  fe/src/App.tsx
  fe/src/api/queryClient.ts
  fe/src/assets/fonts/MapleBold.ttf
  fe/src/assets/fonts/MapleRegular.ttf
  fe/src/assets/fonts/PretendardVariable.woff2
  fe/src/assets/icons/google.svg
  fe/src/assets/icons/logo.svg
  fe/src/assets/images/brand-circle.svg
  fe/src/assets/images/brand.svg
  fe/src/components/Landing/Header.tsx
  fe/src/components/Landing/Main.tsx
  fe/src/components/Landing/index.style.ts
  fe/src/components/common/ThemeSwitch/ThemeSwitch.style.ts
  fe/src/components/common/ThemeSwitch/ThemeSwitch.tsx
  fe/src/layout/index.tsx
  fe/src/main.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handlers.ts
  fe/src/mocks/mswSetup.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/BookClub.tsx
  fe/src/pages/Landing.tsx
  fe/src/pages/Library.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/NotFound.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useTheme.ts
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/theme/ThemeProvider.tsx
  fe/src/styles/theme/palette.ts
  fe/src/styles/theme/typography.ts
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: FE

#9 [BE] 구글 OAuth 토큰, 정보 조회 및 JWT 발급 기능 구현
  be/.gitignore
  be/build.gradle
  be/src/main/java/codesquad/bookkbookk/BookkbookkApplication.java
  be/src/main/java/codesquad/bookkbookk/auth/controller/AuthController.java
  be/src/main/java/codesquad/bookkbookk/auth/data/dto/LoginRequest.java
  be/src/main/java/codesquad/bookkbookk/auth/data/dto/LoginResponse.java
  be/src/main/java/codesquad/bookkbookk/auth/data/dto/OAuthCode.java
  be/src/main/java/codesquad/bookkbookk/auth/data/dto/OAuthTokenResponse.java
  be/src/main/java/codesquad/bookkbookk/auth/data/provider/OAuthProvider.java
  be/src/main/java/codesquad/bookkbookk/auth/data/type/LoginType.java
  be/src/main/java/codesquad/bookkbookk/auth/service/OAuthService.java
  be/src/main/java/codesquad/bookkbookk/jwt/Jwt.java
  be/src/main/java/codesquad/bookkbookk/jwt/JwtProperties.java
  be/src/main/java/codesquad/bookkbookk/jwt/JwtProvider.java
  be/src/main/java/codesquad/bookkbookk/member/data/entity/Member.java
  be/src/main/java/codesquad/bookkbookk/member/repository/MemberRepository.java
  be/src/main/resources/application.yml
  be/src/test/java/codesquad/bookkbookk/BookkbookkApplicationTests.java
Labels: feat, BE

#18 [BE] 멤버 생성,조회, 프로필 수정
  be/build.gradle
  be/src/main/java/codesquad/bookkbookk/auth/controller/AuthController.java
  be/src/main/java/codesquad/bookkbookk/auth/data/dto/AuthCode.java
  be/src/main/java/codesquad/bookkbookk/auth/service/OAuthService.java
  be/src/main/java/codesquad/bookkbookk/image/S3ImageUploader.java
  be/src/main/java/codesquad/bookkbookk/image/s3/S3Config.java
  be/src/main/java/codesquad/bookkbookk/jwt/JwtProvider.java
  be/src/main/java/codesquad/bookkbookk/member/controller/MemberController.java
  be/src/main/java/codesquad/bookkbookk/member/data/dto/MemberResponse.java
  be/src/main/java/codesquad/bookkbookk/member/data/dto/UpdateProfileRequest.java
  be/src/main/java/codesquad/bookkbookk/member/data/entity/Member.java
  be/src/main/java/codesquad/bookkbookk/member/service/MemberService.java
  be/src/test/java/codesquad/bookkbookk/IntegrationTest.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
  be/src/test/java/codesquad/bookkbookk/util/DatabaseCleaner.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#19 [FE] 회원가입, 로그인, 구글 OAuth, 유저 프로필 정보 수정
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/auth/client.ts
  fe/src/api/auth/constants.ts
  fe/src/api/auth/queries.ts
  fe/src/api/auth/type.ts
  fe/src/api/auth/utils.ts
  fe/src/api/fetcher.ts
  fe/src/api/member/client.ts
  fe/src/api/member/constants.ts
  fe/src/api/member/queries.ts
  fe/src/api/member/type.ts
  fe/src/api/queryKeys.ts
  fe/src/api/utils.ts
  fe/src/assets/images/error.svg
  fe/src/assets/images/loading.gif
  fe/src/components/Landing/Header.tsx
  fe/src/components/Landing/Landing.style.ts
  fe/src/components/Landing/Main.tsx
  fe/src/components/SignUp/ProfileEditAvatar.tsx
  fe/src/components/SignUp/SignUp.style.ts
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/SignUp/Title.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/StatusIndicator/StatusIndicator.style.ts
  fe/src/components/common/StatusIndicator/StatusIndicator.tsx
  fe/src/components/common/common.style.ts
  fe/src/constant/index.ts
  fe/src/hooks/useFileReader.tsx
  fe/src/hooks/useMovePage.tsx
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/Landing.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routes/ProtectedRoutes.tsx
  fe/src/routes/Root.tsx
  fe/src/routes/UserProvider.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useMember.ts
  fe/src/store/useTheme.ts
  fe/src/utils/index.ts
  fe/tsconfig.json
Labels: feat, FE

#22 [BE]: 프로그램에 필요한 공통 코드 작성
  be/src/main/java/codesquad/bookkbookk/config/FilterConfig.java
  be/src/main/java/codesquad/bookkbookk/error/ApiExceptionHandler.java
  be/src/main/java/codesquad/bookkbookk/error/exception/ApiException.java
  be/src/main/java/codesquad/bookkbookk/error/exception/ErrorResponse.java
  be/src/main/java/codesquad/bookkbookk/error/exception/MemberNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/filter/CorsFilter.java
  be/src/main/java/codesquad/bookkbookk/filter/JwtFilter.java
  be/src/main/java/codesquad/bookkbookk/jwt/JwtProvider.java
  be/src/main/java/codesquad/bookkbookk/member/controller/MemberController.java
  be/src/main/java/codesquad/bookkbookk/member/service/MemberService.java
  be/src/main/java/codesquad/bookkbookk/resolver/JwtArgumentResolver.java
  be/src/main/java/codesquad/bookkbookk/resolver/MemberId.java
  be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
Labels: feat, BE

#23 [BE] 북클럽 생성, 조회 기능 구현
  be/src/main/java/codesquad/bookkbookk/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/CreateBookClubRequest.java
  be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/CreateBookClubResponse.java
  be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/ReadBookClubResponse.java
  be/src/main/java/codesquad/bookkbookk/bookclub/data/entity/BookClub.java
  be/src/main/java/codesquad/bookkbookk/bookclub/data/entity/MemberBookClub.java
  be/src/main/java/codesquad/bookkbookk/bookclub/repository/BookClubRepository.java
  be/src/main/java/codesquad/bookkbookk/bookclub/repository/MemberBookClubRepository.java
  be/src/main/java/codesquad/bookkbookk/bookclub/service/BookClubService.java
  be/src/main/java/codesquad/bookkbookk/member/data/entity/Member.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#25 [BE]: BE 기본적인 코드와 auth, member, book club 도메인 작성
  be/.gitignore
  be/build.gradle
  be/src/main/java/codesquad/bookkbookk/BookkbookkApplication.java
  be/src/main/java/codesquad/bookkbookk/common/config/FilterConfig.java
  be/src/main/java/codesquad/bookkbookk/common/config/S3Config.java
  be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java
  be/src/main/java/codesquad/bookkbookk/common/error/ApiExceptionHandler.java
  be/src/main/java/codesquad/bookkbookk/common/error/ErrorResponse.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/ApiException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/filter/CorsFilter.java
  be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java
  be/src/main/java/codesquad/bookkbookk/common/image/S3ImageUploader.java
  be/src/main/java/codesquad/bookkbookk/common/jwt/Jwt.java
  be/src/main/java/codesquad/bookkbookk/common/jwt/JwtProperties.java
  be/src/main/java/codesquad/bookkbookk/common/jwt/JwtProvider.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/JwtArgumentResolver.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/MemberId.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/AuthCode.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/LoginRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/LoginResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/OAuthTokenResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/provider/OAuthProvider.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/type/LoginType.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/service/OAuthService.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/CreateBookClubRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/CreateBookClubResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/MemberBookClub.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/MemberBookClubRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
  be/src/main/java/codesquad/bookkbookk/domain/member/controller/MemberController.java
  be/src/main/java/codesquad/bookkbookk/domain/member/data/dto/MemberResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/member/data/dto/UpdateProfileRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/member/data/entity/Member.java
  be/src/main/java/codesquad/bookkbookk/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/member/service/MemberService.java
  be/src/main/resources/application.yml
  be/src/test/java/codesquad/bookkbookk/BookkbookkApplicationTests.java
  be/src/test/java/codesquad/bookkbookk/IntegrationTest.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
  be/src/test/java/codesquad/bookkbookk/util/DatabaseCleaner.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#26 [FE] 공통 페이지 레이아웃
  fe/public/favicon.svg
  fe/src/App.style.ts
  fe/src/api/auth/client.ts
  fe/src/api/auth/constants.ts
  fe/src/api/auth/queries.ts
  fe/src/api/auth/utils.ts
  fe/src/api/member/queries.ts
  fe/src/api/member/type.ts
  fe/src/assets/images/brand-circle.svg
  fe/src/assets/images/brand.svg
  fe/src/components/Landing/Header.tsx
  fe/src/components/Landing/Landing.style.ts
  fe/src/components/Landing/Main.tsx
  fe/src/components/SignUp/ProfileEditAvatar.tsx
  fe/src/components/SignUp/SignUp.style.ts
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/SignUp/Title.tsx
  fe/src/components/common/GoogleLoginButton.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/StatusIndicator/StatusIndicator.style.ts
  fe/src/components/common/common.style.ts
  fe/src/constant/index.ts
  fe/src/layout/AccountPopover.tsx/AccountInfo.tsx
  fe/src/layout/AccountPopover.tsx/AccountPopover.tsx
  fe/src/layout/AccountPopover.tsx/AvatarButton.tsx
  fe/src/layout/AccountPopover.tsx/Popover.tsx
  fe/src/layout/Header.tsx
  fe/src/layout/Layout.style.ts
  fe/src/layout/Layout.tsx
  fe/src/layout/Sidebar.tsx
  fe/src/layout/SidebarItem.tsx
  fe/src/layout/constants.tsx
  fe/src/layout/index.tsx
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/BookClub.tsx
  fe/src/pages/Landing.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/MyPage.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routes/Root.tsx
  fe/src/routes/UserProvider.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/styles/theme/palette.ts
Labels: UI, FE

#28 hotfix: handlers type error 해결을 위한 주석 처리
  fe/src/mocks/handlers.ts
Labels: hotfix

#29 [BE] 책 추가 기능 구현 #15
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookClubNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberNotInBookClubException.java
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/BookClubBook.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookClubBookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/MemberBookClubRepository.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
Labels: feat, BE

#24 [BE] 멤버 프로필 수정 유효성 검증 및 테스트 코드 구현
  be/src/main/java/codesquad/bookkbookk/domain/member/data/dto/MemberResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/member/data/entity/Member.java
  be/src/main/java/codesquad/bookkbookk/domain/member/service/MemberService.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
Labels: feat, BE

#32 [BE] 북클럽 생성 시 이미지 null일 경우 디폴트 이미지 추가
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
Labels: refactor, BE

#30 [FE] 북클럽 생성 기능
  fe/src/api/auth/constants.ts
  fe/src/api/bookClub/client.ts
  fe/src/api/bookClub/constants.ts
  fe/src/api/bookClub/queries.ts
  fe/src/api/bookClub/type.ts
  fe/src/api/member/client.ts
  fe/src/api/member/queries.ts
  fe/src/assets/images/404.png
  fe/src/assets/images/congratulation.png
  fe/src/assets/images/error.png
  fe/src/assets/images/error.svg
  fe/src/components/BookClub/BookClubList.tsx
  fe/src/components/BookClub/BookClubTabs.tsx
  fe/src/components/BookClub/constants.ts
  fe/src/components/Landing/Landing.style.ts
  fe/src/components/Landing/Main.tsx
  fe/src/components/NewBookClub/LeftBox/Congratulation.tsx
  fe/src/components/NewBookClub/LeftBox/Funnel.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
  fe/src/components/NewBookClub/LeftBox/Profile.tsx
  fe/src/components/NewBookClub/LeftBox/Stepper.tsx
  fe/src/components/NewBookClub/NewBookClub.style.ts
  fe/src/components/NewBookClub/RightBox/BookClubCard.tsx
  fe/src/components/NewBookClub/RightBox/BookClubMemberCard.tsx
  fe/src/components/NewBookClub/RightBox/Info.tsx
  fe/src/components/NewBookClub/RightBox/common.style.ts
  fe/src/components/NewBookClub/constants.ts
  fe/src/components/SignUp/ProfileEditAvatar.tsx
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/common/StatusIndicator/StatusIndicator.style.ts
  fe/src/components/common/StatusIndicator/StatusIndicator.tsx
  fe/src/components/common/common.style.ts
  fe/src/constant/index.ts
  fe/src/hooks/useFileReader.tsx
  fe/src/hooks/useFunnel.tsx
  fe/src/hooks/useMovePage.tsx
  fe/src/layout/SidebarItem.tsx
  fe/src/layout/constants.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/BookClub.tsx
  fe/src/pages/NewBookClub.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routes/UserProvider.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useBookClub.ts
  fe/src/store/useMember.ts
Labels: feat, FE

#36 [FE] Sprint #02 프론트 작업
  fe/src/api/auth/constants.ts
  fe/src/api/bookClub/client.ts
  fe/src/api/bookClub/constants.ts
  fe/src/api/bookClub/queries.ts
  fe/src/api/bookClub/type.ts
  fe/src/api/member/client.ts
  fe/src/api/member/queries.ts
  fe/src/assets/images/404.png
  fe/src/assets/images/congratulation.png
  fe/src/assets/images/error.png
  fe/src/assets/images/error.svg
  fe/src/components/BookClub/BookClubList.tsx
  fe/src/components/BookClub/BookClubTabs.tsx
  fe/src/components/BookClub/constants.ts
  fe/src/components/Landing/Landing.style.ts
  fe/src/components/Landing/Main.tsx
  fe/src/components/NewBookClub/LeftBox/Congratulation.tsx
  fe/src/components/NewBookClub/LeftBox/Funnel.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
  fe/src/components/NewBookClub/LeftBox/Profile.tsx
  fe/src/components/NewBookClub/LeftBox/Stepper.tsx
  fe/src/components/NewBookClub/NewBookClub.style.ts
  fe/src/components/NewBookClub/RightBox/BookClubCard.tsx
  fe/src/components/NewBookClub/RightBox/BookClubMemberCard.tsx
  fe/src/components/NewBookClub/RightBox/Info.tsx
  fe/src/components/NewBookClub/RightBox/common.style.ts
  fe/src/components/NewBookClub/constants.ts
  fe/src/components/SignUp/ProfileEditAvatar.tsx
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/common/StatusIndicator/StatusIndicator.style.ts
  fe/src/components/common/StatusIndicator/StatusIndicator.tsx
  fe/src/components/common/common.style.ts
  fe/src/constant/index.ts
  fe/src/hooks/useFileReader.tsx
  fe/src/hooks/useFunnel.tsx
  fe/src/hooks/useMovePage.tsx
  fe/src/layout/SidebarItem.tsx
  fe/src/layout/constants.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/BookClub.tsx
  fe/src/pages/NewBookClub.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routes/UserProvider.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useBookClub.ts
  fe/src/store/useMember.ts
Labels: FE

#40 [FE] 북클럽 생성, 유저 정보 업데이트 개선
  fe/src/api/auth/constants.ts
  fe/src/api/bookClub/client.ts
  fe/src/api/bookClub/constants.ts
  fe/src/api/bookClub/queries.ts
  fe/src/api/bookClub/type.ts
  fe/src/api/member/client.ts
  fe/src/api/member/queries.ts
  fe/src/assets/images/404.png
  fe/src/assets/images/congratulation.png
  fe/src/assets/images/error.png
  fe/src/assets/images/error.svg
  fe/src/components/BookClub/BookClubList.tsx
  fe/src/components/BookClub/BookClubTabs.tsx
  fe/src/components/BookClub/constants.ts
  fe/src/components/Landing/Landing.style.ts
  fe/src/components/Landing/Main.tsx
  fe/src/components/NewBookClub/LeftBox/Congratulation.tsx
  fe/src/components/NewBookClub/LeftBox/Funnel.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
  fe/src/components/NewBookClub/LeftBox/Profile.tsx
  fe/src/components/NewBookClub/LeftBox/Stepper.tsx
  fe/src/components/NewBookClub/NewBookClub.style.ts
  fe/src/components/NewBookClub/RightBox/BookClubCard.tsx
  fe/src/components/NewBookClub/RightBox/BookClubMemberCard.tsx
  fe/src/components/NewBookClub/RightBox/Info.tsx
  fe/src/components/NewBookClub/RightBox/common.style.ts
  fe/src/components/NewBookClub/constants.ts
  fe/src/components/SignUp/ProfileEditAvatar.tsx
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/common/StatusIndicator/StatusIndicator.style.ts
  fe/src/components/common/StatusIndicator/StatusIndicator.tsx
  fe/src/components/common/common.style.ts
  fe/src/constant/index.ts
  fe/src/hooks/useFileReader.tsx
  fe/src/hooks/useFunnel.tsx
  fe/src/hooks/useMovePage.tsx
  fe/src/layout/SidebarItem.tsx
  fe/src/layout/constants.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/BookClub.tsx
  fe/src/pages/NewBookClub.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routes/UserProvider.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useBookClub.ts
  fe/src/store/useMember.ts
Labels: FE

#35 [BE] book entity id isbn으로 변경 및 검증 로직 구현
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
Labels: feat, BE

#44 [BE] 알라딘 책 검색 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/AladinController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadAladinBooksResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/AladinService.java
  be/src/test/java/codesquad/bookkbookk/aladin/integration/AladinTest.java
Labels: feat, BE

#42 [BE] Book Entity 변경사항 구현
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/AladinController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadAladinBookResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/BookClubBook.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookClubBookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/AladinService.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/test/java/codesquad/bookkbookk/aladin/integration/AladinTest.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
Labels: refactor, feat, BE

#47 [BE] JwtFilter 리팩토링, accessToken 재발급 기능 구현
  be/src/main/java/codesquad/bookkbookk/common/config/FilterConfig.java
  be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/RefreshTokenNotSavedException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/BearerPrefixNotIncludedException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/MalformedTokenException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/NoAuthorizationHeaderException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/TokenExpiredException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/TokenNotIncludedException.java
  be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java
  be/src/main/java/codesquad/bookkbookk/common/jwt/JwtProvider.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/Token.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/TokenArgumentResolver.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/ReissueResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/entity/MemberRefreshToken.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/repository/MemberRefreshTokenRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/service/OAuthService.java
  be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
  be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java
Labels: refactor, feat, BE

#46 [BE] 나의 책 목록 조회 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/MemberBook.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/MemberBookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#49 [BE]: 로그아웃 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/repository/MemberRefreshTokenRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/service/OAuthService.java
  be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
Labels: feat, BE

#52 [BE] MutlipartFile null 체크 버그 수정, 멤버 프로필 수정 응답 변경
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
  be/src/main/java/codesquad/bookkbookk/domain/member/controller/MemberController.java
  be/src/main/java/codesquad/bookkbookk/domain/member/data/dto/UpdateProfileResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/member/service/MemberService.java
Labels: hotfix, refactor, BE

#55 [BE]: 페이지네이션 수정
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: refactor, BE

#57 [BE] 토픽 CRUD 기능 및 테스트 코드 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/TopicNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/CreateTopicRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/CreateTopicResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/ReadTopicResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/UpdateTopicTitleRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java
  be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java
Labels: feat, BE

#63 [BE]: 모임 생성 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/gathering/controller/GatheringController.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/data/entity/Gathering.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/repository/GatheringRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java
  be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java
Labels: feat, BE

#66 [FE] 3주차 배포 에러 해결 및 임시 주석 처리
  fe/src/api/constants.ts
  fe/src/components/NewBook/LeftBox/NewBookTabs.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
  fe/src/constant/index.ts
  fe/src/pages/BookClub.tsx
  fe/src/pages/BookDetail.tsx
  fe/src/pages/Library.tsx
Labels: FE

#69 [FE] 책 추가 단계 수정 및 NewBook Atom 모듈 분리
  fe/src/api/book/queries.ts
  fe/src/components/NewBook/LeftBox/BookClubGatheringStep/BookClubChoice.tsx
  fe/src/components/NewBook/LeftBox/BookClubGatheringStep/index.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/BookSearchGuide.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/SearchBookList.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/SearchBookListItem.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/index.tsx
  fe/src/components/NewBook/LeftBox/ChaptersPanel/ChapterList.tsx
  fe/src/components/NewBook/LeftBox/ChaptersPanel/ChapterListItem.tsx
  fe/src/components/NewBook/LeftBox/ChaptersPanel/ChaptersPanel.tsx
  fe/src/components/NewBook/LeftBox/ChaptersPanel/TopicList.tsx
  fe/src/components/NewBook/LeftBox/ChaptersPanel/TopicListItem.tsx
  fe/src/components/NewBook/LeftBox/ChaptersPanel/style.ts
  fe/src/components/NewBook/LeftBox/GatheringPanel/BookClubChoice.tsx
  fe/src/components/NewBook/LeftBox/GatheringPanel/GatheringPanel.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookClubListItem.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookClubModal.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookDetailModal.tsx
  fe/src/components/NewBook/LeftBox/Navigation.tsx
  fe/src/components/NewBook/LeftBox/NewBookTabPanel.tsx
  fe/src/components/NewBook/LeftBox/NewBookTabs.tsx
  fe/src/components/NewBook/LeftBox/SearchPanel/index.tsx
  fe/src/components/NewBook/LeftBox/index.tsx
  fe/src/components/NewBook/RightBox/BookCard.tsx
  fe/src/components/NewBook/RightBox/BookChaptersCard.tsx
  fe/src/components/NewBook/RightBox/BookClubGatheringCard.tsx
  fe/src/components/NewBook/RightBox/index.tsx
  fe/src/components/NewBookClub/LeftBox/Congratulation.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
  fe/src/components/common/Stepper.tsx
  fe/src/components/common/common.style.ts
  fe/src/components/constants.ts
  fe/src/constant/index.ts
  fe/src/layout/SidebarItem.tsx
  fe/src/pages/NewBook.tsx
  fe/src/store/newBook/useBookChoice.ts
  fe/src/store/newBook/useBookClubChoice.ts
  fe/src/store/newBook/useGathering.ts
  fe/src/store/useChapterList.ts
  fe/src/store/useNewBook.ts
  fe/src/store/useTopicList.ts
Labels: refactor, FE

#70 [FE] 서재 페이지 전체 도서 목록 조회
  fe/src/api/book/client.ts
  fe/src/api/book/queries.ts
  fe/src/api/book/type.ts
  fe/src/api/queryKeys.ts
  fe/src/components/Library/BookList/BookCard.tsx
  fe/src/components/Library/BookList/BookCardGrid.tsx
  fe/src/components/Library/BookList/index.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/index.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookDetailModal.tsx
  fe/src/components/NewBook/style.ts
  fe/src/constant/index.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Library.tsx
Labels: feat, FE

#72 [FE] 3주차 프론트 작업 충돌 해결
  fe/src/components/NewBook/LeftBox/NewBookTabs.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
Labels: hotfix, FE

#85 [BE]: Bookmark CUD 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberIsNotBookmarkWriterException.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/CreateBookmarkRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/UpdateBookmarkRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java
  be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE
