Repository bookkbookk/bookkbookk, pull requests merged in 2023-12, with the labels that each got.

#128 [BE] 북마크에 반응 추가/삭제 기능 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkReactionExistsException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkReactionNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/ReactionNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/type/Reaction.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/CreateBookmarkReactionRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/DeleteBookmarkReactionRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java
  be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/BookmarkReaction.java
  be/src/main/java/codesquad/bookkbookk/domain/mapping/repository/BookmarkReactionRepository.java
  be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
Labels: BE

#130 [BE] 코멘트의 반응 추가/삭제 기능 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/CommentReactionExistsException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/CommentReactionNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/CreateCommentReactionRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/DeleteCommentReactionRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java
  be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/CommentReaction.java
  be/src/main/java/codesquad/bookkbookk/domain/mapping/repository/CommentReactionRepository.java
  be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java
Labels: feat, BE

#131 [FE] 북마크/댓글 생성, 수정, 삭제
  fe/package-lock.json
  fe/package.json
  fe/src/api/bookmarks/client.ts
  fe/src/api/bookmarks/queries.ts
  fe/src/api/bookmarks/type.ts
  fe/src/api/comments/client.ts
  fe/src/api/comments/queries.ts
  fe/src/api/comments/type.ts
  fe/src/api/constants.ts
  fe/src/components/BookChapter/LeftBox/BookmarkComment.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/Bookmark.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkCommentList.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkList.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/Bookmark.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/BookmarkCommentList/BookmarkComment.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/BookmarkCommentList/BookmarkCommentList.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/BookmarkThread.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/NewBookmarkComment.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/index.tsx
  fe/src/components/BookChapter/LeftBox/NewBookmark.tsx
  fe/src/components/common/Comment/ActionFooter.tsx
  fe/src/components/common/Comment/ButtonFooter.tsx
  fe/src/components/common/Comment/CommentContent.tsx
  fe/src/components/common/Comment/CommentEditor.tsx
  fe/src/components/common/Comment/CommentHeader.tsx
  fe/src/components/common/Comment/CommentViewer.tsx
  fe/src/components/common/Comment/PageEditor.tsx
  fe/src/components/common/Comment/PageViewer.tsx
  fe/src/components/common/Comment/ReactionMenu.tsx
  fe/src/components/common/Comment/index.tsx
  fe/src/components/common/Comment/style.ts
  fe/src/components/common/CommentTextarea/CommentTextareaFooter.tsx
  fe/src/components/common/CommentTextarea/CommentTextareaWrapper.tsx
  fe/src/components/common/CommentTextarea/ContentField.tsx
  fe/src/components/common/CommentTextarea/index.tsx
  fe/src/constant/index.ts
  fe/src/context/BookmarkList/BookmarkListContext.tsx
  fe/src/context/BookmarkList/BookmarkListProvider.tsx
  fe/src/context/BookmarkList/useBookmarkList.ts
  fe/src/context/CommentList/CommentListContext.tsx
  fe/src/context/CommentList/CommentListProvider.tsx
  fe/src/context/CommentList/useCommentList.ts
  fe/src/context/type.ts
  fe/src/hooks/useAutoScroll.ts
  fe/src/hooks/useInput.ts
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/BookChapter.tsx
  fe/src/styles/theme/palette.ts
  fe/src/utils/constants.ts
  fe/src/utils/index.ts
Labels: feat, FE

#139 [FE] 북마크/댓글 리액션 기능
  fe/src/api/bookmarks/client.ts
  fe/src/api/bookmarks/queries.ts
  fe/src/api/comments/client.ts
  fe/src/api/comments/queries.ts
  fe/src/api/comments/type.ts
  fe/src/api/queryKeys.ts
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/Bookmark.tsx
  fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/BookmarkCommentList/BookmarkComment.tsx
  fe/src/components/BookChapter/LeftBox/ChapterStatusMenu.tsx
  fe/src/components/common/Comment/ActionFooter.tsx
  fe/src/components/common/Comment/ReactionList/ReactionChip.tsx
  fe/src/components/common/Comment/ReactionList/ReactionList.tsx
  fe/src/components/common/Comment/ReactionMenu.tsx
  fe/src/components/common/StatusChip.tsx
  fe/src/components/constants.ts
  fe/src/constant/index.ts
  fe/src/mocks/data.ts
Labels: FE

#140 [BE] path 변경 업데이트
  be/src/main/java/codesquad/bookkbookk/domain/auth/service/AuthorizationService.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/controller/GatheringController.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java
  be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java
  be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java
Labels: refactor, BE

#142 [BE] 북클럽 상태를 이용한 북클럽 조회 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookClubStatusNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ClosedBookClubDetailResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/OpenBookClubDetailResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubDetailResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/type/BookClubStatus.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
  be/src/main/java/codesquad/bookkbookk/domain/member/data/entity/Member.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#144 [BE] 코멘트 목록 조회 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/ReadCommentResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java
  be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#146 [BE] Bookmark/Comment reaction 조회 기능
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadReactionsResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java
  be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
  be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java
Labels: feat, BE

#148 [BE] 멤버 책 조회에서 책의 statusId 주입
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookResponse.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
Labels: feat, BE

#150 [BE] gathering 조회,수정, 삭제 기능 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/GatheringNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/controller/GatheringController.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/ReadGatheringResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/UpdateGatheringRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/UpdateGatheringResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/data/entity/Gathering.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE
