Repository bookkbookk/bookkbookk, pull requests merged in 2023-11, with the labels that each got.

#79 [FE] 책 상세 페이지 새로운 챕터/토픽 추가
  fe/src/api/book/client.ts
  fe/src/api/chapters/client.ts
  fe/src/api/chapters/queries.ts
  fe/src/api/chapters/type.ts
  fe/src/api/queryKeys.ts
  fe/src/components/BookChapters/NewBookChapters/ChapterList.tsx
  fe/src/components/BookChapters/NewBookChapters/ChapterListItem.tsx
  fe/src/components/BookChapters/NewBookChapters/HeaderButtons.tsx
  fe/src/components/BookChapters/NewBookChapters/NewBookChapters.tsx
  fe/src/components/BookChapters/NewBookChapters/TopicList.tsx
  fe/src/components/BookChapters/NewBookChapters/TopicListItem.tsx
  fe/src/components/BookChapters/NewBookChapters/style.ts
  fe/src/components/Landing/Main.tsx
  fe/src/components/Library/BookList/BookCard.tsx
  fe/src/components/Library/BookList/BookCardGrid.tsx
  fe/src/components/Library/Library.style.ts
  fe/src/components/Library/LibraryTabs.tsx
  fe/src/components/NewBook/LeftBox/BookClubGatheringStep/index.tsx
  fe/src/components/SignUp/ProfileEditAvatar.tsx
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/common/GoogleLoginButton.tsx
  fe/src/components/common/TabPanel.tsx
  fe/src/components/common/Tabs.tsx
  fe/src/components/common/common.style.ts
  fe/src/components/constants.ts
  fe/src/constant/index.ts
  fe/src/layout/Header.tsx
  fe/src/layout/HeaderTitle.tsx
  fe/src/layout/SidebarItem.tsx
  fe/src/layout/constants.tsx
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/BookChapters.tsx
  fe/src/pages/BookClub.tsx
  fe/src/pages/BookDetail.tsx
  fe/src/pages/Library.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useChapterList.ts
  fe/src/store/useTopicList.ts
Labels: FE

#89 [FE] 북클럽 멤버 초대 및 참여 기능
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.png
  fe/public/favicon.svg
  fe/src/App.style.ts
  fe/src/api/bookClub/client.ts
  fe/src/api/bookClub/queries.ts
  fe/src/api/bookClub/queries.tsx
  fe/src/api/bookClub/type.ts
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
  fe/src/api/queryKeys.ts
  fe/src/assets/images/brand.png
  fe/src/assets/images/brand.svg
  fe/src/assets/images/welcome.png
  fe/src/components/BookClubJoinGuide.tsx
  fe/src/components/NewBook/LeftBox/BookClubGatheringStep/index.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/index.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookClubModal.tsx
  fe/src/components/NewBook/LeftBox/Navigation.tsx
  fe/src/components/NewBookClub/LeftBox/Congratulation.tsx
  fe/src/components/NewBookClub/LeftBox/Funnel.tsx
  fe/src/components/NewBookClub/LeftBox/Member.tsx
  fe/src/components/NewBookClub/LeftBox/MemberEmailInput.tsx
  fe/src/components/NewBookClub/LeftBox/MemberEmails.tsx
  fe/src/components/NewBookClub/LeftBox/Profile.tsx
  fe/src/components/NewBookClub/RightBox/BookClubMemberCard.tsx
  fe/src/components/SignUp/SignUpForm.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/Navigation.tsx
  fe/src/components/common/common.style.ts
  fe/src/constant/index.ts
  fe/src/hooks/useInput.ts
  fe/src/layout/Header.tsx
  fe/src/layout/HeaderTitle.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/BookClub.tsx
  fe/src/pages/BookClubJoin.tsx
  fe/src/pages/BookClubList.tsx
  fe/src/pages/Landing.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/NotFound.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/store/useBookClub.ts
  fe/src/store/useMember.ts
  fe/src/store/useTheme.ts
  fe/src/styles/theme/palette.ts
  fe/src/utils/index.ts
Labels: feat, FE

#91 [BE]: 초대링크로 북클럽 가입 기능 구현
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberJoinedBookClubException.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/InvitationUrlResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/JoinBookClubRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/JoinBookClubResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClubInvitationCode.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/MemberBookClub.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubInvitationCodeRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubInvitationUrlRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubInvitationService.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubInvitationTest.java
Labels: feat, BE

#93 [BE]: 멤버 책 조회 기능 리팩토링 & 북클럽 책 조회 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookClubBookResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/member/controller/MemberController.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
Labels: refactor, feat, BE

#94 [FE] 북클럽 상세 정보 조회
  fe/src/api/book/client.ts
  fe/src/api/book/queries.ts
  fe/src/api/bookClub/client.ts
  fe/src/api/bookClub/queries.tsx
  fe/src/api/bookClub/type.ts
  fe/src/api/constants.ts
  fe/src/api/member/client.ts
  fe/src/api/member/queries.ts
  fe/src/api/queryKeys.ts
  fe/src/components/BookChapters/NewBookChapters/HeaderButtons.tsx
  fe/src/components/BookClub/GatheringAddModal.tsx
  fe/src/components/BookClub/LeftBox/BookClubInfo.tsx
  fe/src/components/BookClub/RightBox/BookClubMembersCard.tsx
  fe/src/components/Library/BookList/index.tsx
  fe/src/components/Library/Library.style.ts
  fe/src/components/NewBook/LeftBox/Modals/BookClubModal.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookDetailModal.tsx
  fe/src/components/NewBook/style.ts
  fe/src/components/NewBookClub/LeftBox/MemberEmails.tsx
  fe/src/components/common/common.style.ts
  fe/src/layout/HeaderTitle.tsx
  fe/src/mocks/data.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/BookChapters.tsx
  fe/src/pages/BookClub.tsx
  fe/src/pages/BookClubJoin.tsx
  fe/src/pages/Library.tsx
  fe/src/pages/Main.tsx
  fe/src/routes/constants.ts
  fe/src/routes/router.tsx
  fe/src/utils/index.ts
Labels: FE

#96 [BE] BE 4주차 작업
  be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/CommentNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberIsNotBookmarkWriterException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberIsNotCommentWriterException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberJoinedBookClubException.java
  be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookClubBookResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/InvitationUrlResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/JoinBookClubRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/JoinBookClubResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClubInvitationCode.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/MemberBookClub.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubInvitationCodeRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubInvitationUrlRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubInvitationService.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/CreateBookmarkRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/UpdateBookmarkRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/ReadChapterResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/UpdateChapterTitleRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/CreateCommentRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/UpdateCommentRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/repository/CommentRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java
  be/src/main/java/codesquad/bookkbookk/domain/member/controller/MemberController.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubInvitationTest.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
  be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java
  be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
  be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: BE, release

#98 [FE] 4주차 프론트 배포 에러 해결
  fe/src/api/book/client.ts
Labels: FE

#101 [FE] 북클럽 새로운 모임 생성 기능
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/book/type.ts
  fe/src/api/bookClub/client.ts
  fe/src/api/bookClub/queries.tsx
  fe/src/api/constants.ts
  fe/src/api/gatherings/client.ts
  fe/src/api/gatherings/queries.tsx
  fe/src/api/gatherings/type.ts
  fe/src/api/queryKeys.ts
  fe/src/components/BookClub/GatheringAddModal.tsx
  fe/src/components/BookClub/GatheringAddModal/CheckGatherings.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringAddModal.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringBookChoice/BookClubBookItem.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringBookChoice/GatheringBookChoice.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/GatheringForm.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/GatheringInfo.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/GatheringTable/GatheringEditTableBody.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/GatheringTable/GatheringTable.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/GatheringTable/GatheringTableItem.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/GatheringTable/GatheringTableItemCell.tsx
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/style.ts
  fe/src/components/BookClub/GatheringAddModal/GatheringInfo/type.ts
  fe/src/components/Library/BookList/BookCard.tsx
  fe/src/components/NewBook/LeftBox/BookClubGatheringStep/index.tsx
  fe/src/components/NewBook/LeftBox/BookSearchStep/SearchBookListItem.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookClubListItem.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookClubModal.tsx
  fe/src/components/NewBook/LeftBox/Modals/BookDetailModal.tsx
  fe/src/components/NewBook/RightBox/BookCard.tsx
  fe/src/components/NewBook/RightBox/BookClubGatheringCard.tsx
  fe/src/components/NewBook/style.ts
  fe/src/components/common/BookInfo.tsx
  fe/src/components/common/Navigation.tsx
  fe/src/components/common/Stepper.tsx
  fe/src/components/common/common.style.ts
  fe/src/components/constants.ts
  fe/src/constant/index.ts
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/BookClub.tsx
  fe/src/store/newBook/useGathering.ts
  fe/src/store/useGathering.ts
  fe/src/utils/index.ts
Labels: feat, FE

#107 [BE] 북클럽 상세 조회 기능 구현
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/type/BookStatus.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ClosedBookClubDetailResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/OpenBookClubDetailResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubDetailResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/type/BookClubStatus.java
  be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
  be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java
  be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/BookClubMember.java
  be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#110 [BE] refresh token http-only cookie에 담아서 전달하게 코드 변경
  be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/RefreshTokenNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshToken.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenArgumentResolver.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java
  be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/LoginResponse.java
  be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
Labels: feat, BE

#111 [BE] refresh token cookie 만료시간 추가, 로그아웃 시 set-cookie 구현
  be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java
  be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
Labels: feat, BE

#114 [BE] Exception에 error code 추가
  be/src/main/java/codesquad/bookkbookk/common/error/ErrorResponse.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/ApiException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/RefreshTokenNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/AuthException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/BearerPrefixNotIncludedException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/MalformedTokenException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/NoAuthorizationHeaderException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/TokenExpiredException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/TokenNotIncludedException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/BearerPrefixNotIncludedException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/MalformedTokenException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/NoAuthorizationHeaderException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/TokenExpiredException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/TokenNotIncludedException.java
  be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java
  be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenArgumentResolver.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
  be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
  be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java
  be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java
  be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java
  be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
Labels: feat, BE

#119 [BE] 챕터 조회 기능 수정
  be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterStatusNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/ReadChapterResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/type/ChapterStatus.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java
  be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java
  be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java
  be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
Labels: feat, BE

#124 [BE] BookStatus, ChapterStatus 통합 & Status 변경 기능 추가
  be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterStatusNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/error/exception/StatusNotFoundException.java
  be/src/main/java/codesquad/bookkbookk/common/type/Status.java
  be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/UpdateBookStatusRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/UpdateBookStatusResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java
  be/src/main/java/codesquad/bookkbookk/domain/book/data/type/BookStatus.java
  be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/UpdateChapterRequest.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/UpdateChapterResponse.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/data/type/ChapterStatus.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterRepository.java
  be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java
  be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
  be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java
  be/src/test/java/codesquad/bookkbookk/type/StatusTest.java
Labels: feat, BE
